baseURL = 'https://joseantequera.github.io/notas/'
languageCode = 'es'
title = '00JoseNotas'
theme = 'Ananke Gohugo Theme'
PublishDir = 'docs'
[params]
read_more_copy = "leer mas"
site_logo = "images/notas.png"